name: Smart Contracts CI
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
        shell: bash
      - name: Compile
        run: npx hardhat compile
      - name: Unit Tests
        run: npx hardhat test
