name: Smart Contracts CI
on:
  workflow_dispatch:
  push:
  pull_request:

env:
  WALLET_ADDRESS: ${{ secrets.WALLET_ADDRESS }}
  WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  OPTIMISM_API_URL: ${{ secrets.OPTIMISM_API_URL }}
  POLYGON_API_URL: ${{ secrets.POLYGON_API_URL }}

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm install
        shell: bash
      - name: Compile
        run: npx hardhat compile
      - name: Unit Tests
        run: npx hardhat test
